version: '3.8'

services:
  angular-dev:
    container_name: mindata-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
