# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Instalar Angular CLI global si hace falta
RUN npm install -g @angular/cli

EXPOSE 4200

CMD ["npm", "start"]
